name: Check Minimum Score

on :
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'

permissions:
  contents: read

jobs:
  
  Train:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.prepare.outputs.image-tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare image tag
        id: prepare
        run: echo "::set-output name=image-tag::$(echo ${{ github.sha }})"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_assignment:${{ steps.prepare.outputs.image-tag }}

  Test:
    needs: Train
    runs-on: ubuntu-latest
    if: ${{ needs.build-and-train.outputs.image-tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull and run Docker image
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_assignment:${{ needs.build-and-train.outputs.image-tag }}
          docker run --name test-container ${{ secrets.DOCKER_HUB_USERNAME }}/cicd_assignment:${{ needs.build-and-train.outputs.image-tag }}

      - name: Check test results
        run: |
          result=$(docker logs test-container)
          echo "Test results: $result"
          if [[ "$result" != *'Score: 0.50'* ]]; then
            echo "Test failed with score less than 0.50"
            exit 1
          fi
